### ISSUE TITLE
Balatro Save file Corrupts when ran imported and exported

### ISSUE THREAD

**Issue by ryanthomsen** [WilsontheWolf/balatro-save-loader#2]
Just tossing this here for tracking.
After importing save into editor and exporting save file corrupts everytime without edits.
Sha 256 hash from https://emn178.github.io/online-tools/sha256_checksum.html is broken.

Original Save File Hash: 
f1866e539b8f824575405b92e6b833630ad5633417ecd30467e6375ed75cf157

Hash after importing and exporting without edits:
858796b970843bddad7ed1c5c331e7d27d6245d3b320a14d99eec76d6394f0cf

![image](https://github.com/WilsontheWolf/balatro-save-loader/assets/82417326/06a4d465-b29f-4edc-8a14-70fb51bdec30)

**Comment by ryanthomsen** [comment]
when trying to export the corrupted save file again I get the following error:
C:\Users\rthom\Downloads\BalatroSaveEditor-main>python main.py export bAXKUP\save.jkr -o blank.jkr
Traceback (most recent call last):
  File "C:\Users\rthom\Downloads\BalatroSaveEditor-main\main.py", line 137, in <module>
    main()
  File "C:\Users\rthom\Downloads\BalatroSaveEditor-main\main.py", line 129, in main
    export(args.file, args.output)
  File "C:\Users\rthom\Downloads\BalatroSaveEditor-main\main.py", line 104, in export
    data = parse(file_name)
  File "C:\Users\rthom\Downloads\BalatroSaveEditor-main\main.py", line 68, in parse
    return decompress(file_name)
  File "C:\Users\rthom\Downloads\BalatroSaveEditor-main\utils.py", line 60, in decompress
    return parse_obj(decompress_raw(file_name))
  File "C:\Users\rthom\Downloads\BalatroSaveEditor-main\utils.py", line 16, in decompress_raw
    decompressed_data = decompressor.decompress(data)
zlib.error: Error -3 while decompressing data: invalid block type

**Comment by ryanthomsen** [comment]
Realiezed this was for TeddyHuangs editor which appears to have corrupted my save.
I will close this out apologies for inconvenience
